WebCDA/Models/ErrorViewModel.cs
namespace WebCDA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebCDA/Controllers/BidonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebCDA.Controllers
{
    public class BidonController : Controller
    {
        // GET: BidonController
        public ActionResult Index()
        {
            return View();
        }

        // GET: BidonController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BidonController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BidonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BidonController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BidonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BidonController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BidonController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebCDA/Controllers/EtudiantsController.cs
using BusinessLayer;
using Castle.Windsor;
using DataRepository;
using IBusinessLayer;
using IDataRepository;
using Microsoft.AspNetCore.Mvc;
using Models;


namespace WebCDA.Controllers
{
    public class EtudiantsController : Controller
    {


        private static WindsorContainer InitDependency()
        {
            var container = new WindsorContainer();
            container.Register(Castle.MicroKernel.Registration.Component.For<IEtudiantRepository>().ImplementedBy<EtudiantRepository>());
            container.Register(Castle.MicroKernel.Registration.Component.For<IEtudiantBL>().ImplementedBy<EtudiantBL>());
            return container;
        }

        IEtudiantBL context = InitDependency().Resolve<IEtudiantBL>();




        //-------------------------------------------------------------------------


        // GET: StudentsController
        public ActionResult Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var etudiants = context.GetEleves().ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                etudiants = etudiants.Where(e => e.Nom.Contains(searchString)).ToList();
            }

            return View(etudiants);
        }

        //// GET: EtudiantsController/Details/5
        // GET: EtudiantsController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var etudiants = await context.GetEleveById(id);
            if (etudiants == null)
            {
                return NotFound();
            }
            return View(etudiants);
        }

        // GET: EtudiantsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EtudiantsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Etudiant stu)
        {
            try
            {
                await context.CreateEleve(stu);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: EtudiantsController/Edit
        public async Task<ActionResult> Edit(int id)
        {
            var etudiants = await context.GetEleveById(id);
            if (etudiants == null)
            {
                return NotFound();
            }
            return View(etudiants);
        }

        // POST: EtudiantsController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Edit(int id, Etudiant stu)
        {
            try
            {
                await context.UpdateEleve(stu);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: EtudiantsController/Delete
        public async Task<ActionResult> Delete(int id)
        {
            var etudiants = await context.GetEleveById(id);
            if (etudiants == null)
            {
                return NotFound();
            }
            return View(etudiants);
        }

        // POST: EtudiantsController/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await context.DeleteEleve(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }

}

WebCDA/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebCDA.Models;

namespace WebCDA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebCDA/Views/Etudiants/Create.cshtml
@model Models.Etudiant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebCDA/Views/Etudiants/Delete.cshtml
@model Models.Etudiant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Etudiant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebCDA/Views/Etudiants/Details.cshtml
@model Models.Etudiant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Etudiant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebCDA/Views/Etudiants/Edit.cshtml
@model Models.Etudiant

@{
    ViewData["Title"] = "Edit";
}




<h1>Edit Etudiant</h1>

<h4>Etudiant</h4>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebCDA/Views/Etudiants/Index.cshtml
@model IEnumerable<Models.Etudiant>

@{
    ViewData["Title"] = "Gestion des Elèves";
}

<h1>Gestion des élèves</h1>

<form asp-action="Index" method="get">
    <p>
        Nom: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
        <input type="submit" value="Rechercher" />
    </p>
</form>

<p>
    <a asp-action="Create">Créer un nouvel élève</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenom)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Modifier</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Détails</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebCDA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebCDA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCDA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCDA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCDA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Etudiants" asp-action="Index">Gestion des Eleves</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebCDA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>